theme: jekyll-theme-cayman
title: Uncovering the Connections Between Adversarial Transferability and Knowledge Transferability
description: Kaizhao Liang*, Jacky Y.Zhang*, Boxin Wang, Zhuolin Yang, Sanmi Koyejo, Bo Li (* equal contribution)
