theme: jekyll-theme-slate
title: Does Adversarial Transferability Indicate Knowledge Transferability?
description: <a href="https://kaizhaoliang.github.io/Portfolio/" >Kaizhao Liang*</a>, <a href="https://yiboz.me/" >Jacky Y.Zhang*</a>, <a href="http://sanmi.cs.illinois.edu/" >Sanmi Koyejo</a>, <a href="https://aisecure.github.io/" >Bo Li</a> (* equal contribution)
