theme: jekyll-theme-hacker
title: Does Adversarial Transferability Indicate Knowledge Transferability?
description: <a href="https://kaizhaoliang.github.io/Portfolio/" class="link-gray-dark">Kaizhao Liang*</a>, <a href="https://yiboz.me/" class="link-gray-dark">Jacky Y.Zhang*</a>, <a href="http://sanmi.cs.illinois.edu/" class="link-gray-dark">Sanmi Koyejo</a>, <a href="https://aisecure.github.io/" class="llink-gray-dark">Bo Li</a> (* equal contribution)
