theme: jekyll-theme-cayman
title: Does Adversarial Transferability Indicate Knowledge Transferability?
description: <a href="https://kaizhaoliang.github.io/Portfolio/" class="link-grey">Kaizhao Liang*</a>, <a href="https://yiboz.me/" class="link-grey">Jacky Y.Zhang*</a>, <a href="http://sanmi.cs.illinois.edu/" class="link-grey">Sanmi Koyejo</a>, <a href="https://aisecure.github.io/" class="link-grey">Bo Li</a> (* equal contribution)
